### ISSUE TITLE
chrono::NaiveDate only shows the year

### ISSUE THREAD

**Issue by bbigras** [DarrenTsung/rust-pretty-assertions-sorted#1]
I'm comparing 2 `HashMap` with `assert_eq_sorted!()` and I only see the year.

Like `"key": 2022,`.

Could rust-pretty-assertions-sorted handle `chrono::NaiveDate`?

**Comment by DarrenTsung** [comment]
Hi @bbigras, please try updating to `1.2.0` and let me know if it works. This commit should add better handling for `chrono::NaiveDate`: https://github.com/DarrenTsung/rust-pretty-assertions-sorted/commit/c61c36369ec49d4656af07f027f1fa2380dae7df

**Comment by bbigras** [comment]
It works and it's awesome! Thank you so much!

![image](https://user-images.githubusercontent.com/24027/169541376-6a40b82d-4356-4e18-819d-e97498b935c2.png)
